format_version: 10
pipelines:
  test_pipeline1:
    environment_variables:
      DEPLOYMENT: test
    secure_variables:
      ENV_PASSWORD: "test-password"
    group: defaultGroup
    materials:
      git_repo:
        git: https://github.com/Manikaran1996/gocd-test-sample-project.git
        branch: master
    stages:
    - build-stage:
        jobs:
          - exec-job:
              tasks:
              - exec:
                  command: ./scripts/run.sh
                  arguments:
                  - Runtime args
